In [10]:
import scanpy as sc
import os
import pandas as pd
import numpy as np
import anndata as ad
import seaborn as sns
from matplotlib import pyplot as plt
from glob import glob

In [2]:
human_adata = sc.read_h5ad("data/human_subsetted.h5ad")

In [5]:
sample_list = ["data/SNS2-2.h5ad", "data/SNS3_1.h5ad", "data/SNS3_2.h5ad", "data/SNS3_4.h5ad"]

In [8]:
mouse_adatas = [sc.read_h5ad(path) for path in sample_list]

In [11]:
mouse_adata = ad.concat(mouse_adatas, join="outer", label="batch", keys=sample_list)

In [21]:
human_adata.obs

                         sample cell_type_high_resolution cell_type
AAACGCTAGTGAACAT-1-1   50410319                 Ast DPP10       Ast
AAAGGATAGGATATGT-1-1   50410319                 Ast DPP10       Ast
AAAGGGCCAGGCATGA-1-1   50410319                 Ast DPP10       Ast
AAAGGGCGTATTCTCT-1-1   50410319                 Ast DPP10       Ast
AAAGTCCAGCTGCGAA-1-1   50410319                  Ast GRM3       Ast
...                         ...                       ...       ...
TTACTGTTCCTCTAGC-43-1  94430339                       Per       Per
TTCAATCCACGTACAT-43-1  94430339                       End       End
TTGCGTCTCCATCACC-43-1  94430339                       Per       Per
TTGTTCAAGGGACACT-43-1  94430339                       End       End
TTGTTTGAGCATGCAG-43-1  94430339                       Fib       Fib

[19666 rows x 3 columns]

In [19]:
mouse_adata.obs

,sample,nCount_RNA,nFeature_RNA,percent.mt,nCount_SCT,nFeature_SCT,SCT_snn_res.1,seurat_clusters,samples_clusters,cell_type,batch
AAACCTGAGCGTGTCC-1_2,SNS2-2,2389,1385,0.000000,3129,1366,14,14,14,Inhibitary_neurons,data/SNS2-2.h5ad
AAACCTGAGTCAAGGC-1_2,SNS2-2,5729,2466,0.017455,4447,2424,5,5,5,Excitatory_neurons,data/SNS2-2.h5ad
AAACCTGCAACGCACC-1_2,SNS2-2,4786,2365,0.292520,4320,2339,7,7,7,Inhibitary_neurons,data/SNS2-2.h5ad
AAACCTGCACAGGAGT-1_2,SNS2-2,5169,2513,0.019346,4426,2483,18,18,18,Excitatory_neurons,data/SNS2-2.h5ad
AAACCTGCACGAAAGC-1_2,SNS2-2,3701,1890,0.000000,3713,1877,20,20,20,Excitatory_neurons,data/SNS2-2.h5ad
...,...,...,...,...,...,...,...,...,...,...,...
TTTGTCATCCAAATGC-1_7,SNS3_4,766,462,0.000000,1740,545,0,0,0,Astrocytes,data/SNS3_4.h5ad
TTTGTCATCCGTCAAA-1_7,SNS3_4,577,291,0.000000,1809,440,11,11,11,Oligodendrocytes,data/SNS3_4.h5ad
TTTGTCATCTAACTTC-1_7,SNS3_4,6693,2558,0.029882,2912,1697,24,24,24,Excitatory_neurons,data/SNS3_4.h5ad
TTTGTCATCTCCCTGA-1_7,SNS3_4,3649,1691,0.082214,2920,1652,9,9,9,Excitatory_neurons,data/SNS3_4.h5ad
TTTGTCATCTTCTGGC-1_7,SNS3_4,725,404,0.137931,1799,499,0,0,0,Astrocytes,data/SNS3_4.h5ad

In [17]:
human_adata.obs.rename(columns={"major_cell_type":"cell_type"}, inplace=True)
human_adata.obs.rename(columns={"projid":"sample"}, inplace=True)
mouse_adata.obs.rename(columns={"orig.ident":"sample"}, inplace=True)

In [23]:
mouse_adata.write("data/mouse.h5ad")
human_adata.write("data/human.h5ad")