In [1]:
# Make the csv
import pandas as pd

df = pd.DataFrame(columns=["path", "species", "embedding_path"])
df["species"] = ["zebrafish", "frog"]
df["path"] = ["data/zebrafish.h5ad", "data/frog.h5ad"]

##### CHANGE THESE PATHS #####
zebrafish_embedding_path = "/restricted/projectnb/czproj/A00/jlhan/saturn/data/protein_embeddings_export/ESM2/zebrafish_embedding.torch"
frog_embedding_path = "/restricted/projectnb/czproj/A00/jlhan/saturn/data/protein_embeddings_export/ESM2/frog_embedding.torch"
##############################
df["embedding_path"] = [zebrafish_embedding_path, frog_embedding_path]
df.to_csv("data/zebrafish_frog_run.csv", index=False)
df

,path,species,embedding_path
0,data/zebrafish.h5ad,zebrafish,/restricted/projectnb/czproj/A00/jlhan/saturn/...
1,data/frog.h5ad,frog,/restricted/projectnb/czproj/A00/jlhan/saturn/...

In [2]:
pd.read_csv("data/frog_zebrafish_cell_type_map.csv").head(10)

   Unnamed: 0            frog_cell_type       zebrafish_cell_type
0           0                  Blastula                       NaN
1           1                  Germline                  Germline
2           2             Neuroectoderm             Neuroectoderm
3           3       Non-neural ectoderm       Non-neural ectoderm
4           4  Involuting marginal zone  Involuting marginal zone
5           5         Spemann organizer                       NaN
6           6                  Endoderm                  Endoderm
7           7      Epidermal progenitor      Epidermal progenitor
8           8                  Ionocyte                  Ionocyte
9           9               Goblet cell                       NaN